apiVersion: v1
kind: Service
metadata:
  name: image-processing-service
spec:
  selector:
    app: image-processing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
