apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processing-service
  template:
    metadata:
      labels:
        app: image-processing-service
    spec:
      containers:
      - name: image-processing-container
        image: gcr.io/diesel-environs-435423-j6/image-processing-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "image_processing_service.settings"
